ゲーム終了の処理を追加
sorude26/ps20a-network pull request #13
Opened 2021-06-22 04:14 UTC by yoshocho

・stageテスト用のシーンの配置等の設定を行った
・キャラクターの死亡時の処理を追加設定した
・ゲームマネージャーのイベントを外部からの呼べるようにした。　

2021-06-22 04:21 UTC, dsuz requested changes

2021-06-22 04:21 UTC, dsuz commented on Assets/Scripts/takeuchi/GameManagerTest.cs
> +    IDied = 150 //私は死んだ
XMLコメントでお願いします。

2021-06-22 04:21 UTC, dsuz commented on Assets/Scripts/takeuchi/PlayerDeath.cs
> +                GameOvaer();
GameOver に変更してください。

2021-06-22 04:29 UTC, yoshocho commented on Assets/Scripts/takeuchi/PlayerDeath.cs
> +                GameOvaer();
直しました。

2021-06-22 06:22 UTC, dsuz requested changes

2021-06-22 06:22 UTC, dsuz commented on Assets/prefab/GameZoon.prefab
> +  m_TagString: GameZoon
指摘もれしてすみません。これも "GameZone" に直してください。

2021-06-23 05:10 UTC, yoshocho commented on Assets/prefab/GameZoon.prefab
> +  m_TagString: GameZoon
直しました。

2021-06-29 01:23 UTC, merged